<?php
/**
 * Template part for displaying user reviews (static version).
 *
 * @package BestMebel
 */

// Placeholder data for reviews
$reviews = array(
    array(
        'photo_url' => 'https://placehold.co/60x60/E0E0E0/777?text=User1',
        'name' => 'Екатерина Иванова',
        'date' => '15.03.2024',
        'text' => 'Очень довольна качеством дивана "Атлант"! Удобный, красивый, идеально вписался в интерьер. Сборка была быстрой и аккуратной. Рекомендую!',
        'item_name' => 'Диван "Атлант"'
    ),
    array(
        'photo_url' => 'https://placehold.co/60x60/D0D0D0/666?text=User2',
        'name' => 'Алексей Петров',
        'date' => '12.03.2024',
        'text' => 'Заказывал кухонный гарнитур "Модерн". Привезли в срок, все комплектующие на месте. Смотрится отлично, функциональность на высоте. Спасибо BestMebel!',
        'item_name' => 'Кухонный гарнитур "Модерн"'
    ),
    array(
        'photo_url' => 'https://placehold.co/60x60/C0C0C0/555?text=User3',
        'name' => 'Мария Сидорова',
        'date' => '10.03.2024',
        'text' => 'Приобрела комод "Винтаж". Очень стильный и вместительный. Фурнитура качественная. Единственное, доставка немного задержалась, но в целом довольна.',
        'item_name' => 'Комод "Винтаж"'
    )
);
?>
<section class="user-reviews-section">
    <div class="container">
        <h2 class="section-title"><?php esc_html_e( 'Отзывы пользователей', 'bestmebel' ); ?></h2>
        <div class="reviews-slider-wrapper"> <?php // This will be targeted by JS later ?>
            <?php foreach ( $reviews as $review ) : ?>
                <div class="review-card">
                    <div class="review-header">
                        <img src="<?php echo esc_url( $review['photo_url'] ); ?>" alt="<?php echo esc_attr( $review['name'] ); ?>" class="reviewer-photo">
                        <div class="reviewer-info">
                            <span class="reviewer-name"><?php echo esc_html( $review['name'] ); ?></span>
                            <span class="review-date"><?php echo esc_html( $review['date'] ); ?></span>
                        </div>
                    </div>
                    <div class="review-body">
                        <p><?php echo esc_html( $review['text'] ); ?></p>
                    </div>
                    <div class="review-footer">
                        <span class="reviewed-item-name"><?php esc_html_e( 'Товар:', 'bestmebel' ); ?> <?php echo esc_html( $review['item_name'] ); ?></span>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="slider-dots-navigation">
            <?php // Placeholder for dots - will be generated by JS or styled spans ?>
            <span class="dot active"></span>
            <span class="dot"></span>
            <span class="dot"></span>
        </div>
    </div>
</section>
