<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<!DOCTYPE html>
<html lang="<?=LANGUAGE_ID?>">
<head>
    <meta charset="UTF-8"> <?/* TODO: Should be <?=SITE_CHARSET?> or similar Bitrix constant */?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?$APPLICATION->ShowTitle()?></title>
    <?$APPLICATION->ShowHead();?>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <?$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH . "/style.css");?>
</head>
<body>
    <?$APPLICATION->ShowPanel();?>
    <div class="page-wrapper">
        <header class="site-header">
            <div class="header-content grid-container">
                <div class="logo-container col-3">
                    <div class="logo-graphic">
                        <span class="graphic-bar bar-green"></span>
                        <span class="graphic-bar bar-orange"></span>
                        <span class="graphic-bar bar-yellow"></span>
                    </div>
                    <a href="/" class="logo-text">BestMebel</a>
                </div>

                <div class="search-container col-6">
                    <form action="/search" method="get" class="search-form">
                        <input type="search" name="query" placeholder="Поиск среди 90 000 товаров" class="search-input">
                        <button type="submit" class="search-button" aria-label="Поиск">
                            <svg class="search-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="20px" height="20px"><path d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/></svg>
                        </button>
                    </form>
                </div>

                <div class="contact-actions-container col-3">
                    <div class="contact-info">
                        <a href="tel:+70000000000" class="phone-number">+7 (000) 000-00-00</a>
                        <span class="working-hours">Пн-Пт: 10:00 - 20:00</span>
                    </div>
                    <div class="user-actions">
                        <a href="/profile" aria-label="Профиль" class="action-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="24px" height="24px"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>
                        </a>
                        <a href="/favorites" aria-label="Избранное" class="action-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="24px" height="24px"><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>
                        </a>
                        <a href="/cart" aria-label="Корзина" class="action-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="24px" height="24px"><path d="M7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zM1 2v2h2l3.6 7.59-1.35 2.45c-.16.28-.25.61-.25.96 0 1.1.9 2 2 2h12v-2H7.42c-.14 0-.25-.11-.25-.25l.03-.12.9-1.63h7.45c.75 0 1.41-.41 1.75-1.03l3.58-6.49A1.003 1.003 0 0 0 20 4H5.21l-.94-2H1zm16 16c-1.1 0-1.99.9-1.99 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/></svg>
                        </a>
                    </div>
                    <button type="button" class="btn btn-primary btn-order-call">Заказать звонок</button>
                </div>
            </div>
        </header>
        <nav class="main-navigation">
            <div class="nav-content grid-container">
                <?$APPLICATION->IncludeComponent(
                    "bitrix:menu", 
                    "horizontal_multilevel", // Using a standard template for now
                    array(
                        "ROOT_MENU_TYPE" => "top",  // Corresponds to the menu type to be created in Bitrix admin
                        "MAX_LEVEL" => "1",         // For a single-level horizontal menu
                        "CHILD_MENU_TYPE" => "left",// Not used if MAX_LEVEL is 1
                        "USE_EXT" => "N",           // Set to Y if menu items are generated by other components
                        "DELAY" => "N",             // N - build menu immediately
                        "ALLOW_MULTI_SELECT" => "N",// N - disallow multiple items to be active
                        "MENU_CACHE_TYPE" => "A",   // A - Auto cache if settings allow, N - no cache, Y - cache
                        "MENU_CACHE_TIME" => "360000", // Cache time in seconds (100 hours)
                        "MENU_CACHE_USE_GROUPS" => "Y", // Y - cache per user group
                        "MENU_CACHE_GET_VARS" => array(), // Additional variables affecting cache
                        "COMPONENT_TEMPLATE" => "horizontal_multilevel"
                    ),
                    false
                );?>
            </div>
        </nav>
        <div class="page-body-container grid-container"> 
            <aside class="sidebar-catalog col-3">
                <h3>Каталог мебели</h3>
                <!-- TODO: BITRIX_SIDEBAR_CATALOG_LIST_START - Replace static list below with a bitrix:catalog.section.list component call and custom template. -->
                <ul class="category-list">
                    <li><a href="#"><!-- Icon placeholder --> Гостинные</a></li> <?/* TODO: Replace with bitrix:catalog.section.list */?>
                    <li><a href="#"><!-- Icon placeholder --> Кухни</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Спальни</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Ванные</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Прихожие</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Мебель для офиса</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Стеллажи</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Комоды</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Детская мебель</a></li>
                    <li><a href="#"><!-- Icon placeholder --> Мягкая мебель</a></li>
                </ul>
                <!-- TODO: BITRIX_SIDEBAR_CATALOG_LIST_END -->
                <!-- TODO: BITRIX_SIDEBAR_SALES_LEADERS_START - Replace static content below with a Bitrix component (e.g., bitrix:iblock.element.list or a custom component for sales leaders). -->
                <section class="sales-leaders-sidebar">
                    <h3 class="sidebar-section-title">Лидеры продаж</h3>
                    <div class="sales-leader-items">
                         <?/* TODO: Replace with Bitrix component for sales leaders */?>
                        <a href="#" class="sales-leader-item">
                            <img src="https://via.placeholder.com/70x70/F5F5F5/555?text=Hit+1" alt="Лидер продаж 1">
                            <div class="item-details">
                                <h4 class="item-name">Элегантный комод "Винтаж"</h4>
                                <div class="item-rating"><span>⭐</span><span>⭐</span><span>⭐</span><span>⭐</span><span>☆</span></div>
                                <div class="item-price"><span class="current-price">2 990 ₽</span><span class="old-price">3 500 ₽</span></div>
                            </div>
                        </a>
                        <a href="#" class="sales-leader-item">
                            <img src="https://via.placeholder.com/70x70/F5F5F5/555?text=Hit+2" alt="Лидер продаж 2">
                            <div class="item-details">
                                <h4 class="item-name">Кресло "Комфорт Плюс"</h4>
                                <div class="item-rating"><span>⭐</span><span>⭐</span><span>⭐</span><span>⭐</span><span>⭐</span></div>
                                <div class="item-price"><span class="current-price">1 450 ₽</span><span class="old-price">1 800 ₽</span></div>
                            </div>
                        </a>
                        <a href="#" class="sales-leader-item">
                            <img src="https://via.placeholder.com/70x70/F5F5F5/555?text=Hit+3" alt="Лидер продаж 3">
                            <div class="item-details">
                                <h4 class="item-name">Стол обеденный "Лофт"</h4>
                                <div class="item-rating"><span>⭐</span><span>⭐</span><span>⭐</span><span>⭐</span><span>☆</span></div>
                                <div class="item-price"><span class="current-price">5 800 ₽</span></div>
                            </div>
                        </a>
                    </div>
                </section>
                <!-- TODO: BITRIX_SIDEBAR_SALES_LEADERS_END -->
                <?// NOTE: The User Reviews section was incorrectly nested here in the source index.html. ?>
                <?// It should be in the main content area. This will be addressed when converting that section. ?>
            </aside>
            <main class="main-content col-9">
                <?/* Page specific content will be included here by Bitrix ($APPLICATION->IncludeComponent, etc.) */?>
